import fs from 'fs';

const data = {
  "Taiwan": { "flag": "🇹🇼", "colors": ["Red","Blue","White"], "capital": "Taipei", "region": "Asia", "knownFor": "Leading producer of advanced semiconductors", "sizeDesc": "36,193 km²; mountainous island nation off the coast of China", "popDesc": "23.5 million; densely populated and highly developed tech workforce" },
  "Malaysia": { "flag": "🇲🇾", "colors": ["Yellow","Blue","Red","White"], "capital": "Kuala Lumpur", "region": "Asia", "knownFor": "Petronas Twin Towers and diverse cultural heritage", "sizeDesc": "330,803 km²; divided into Peninsular Malaysia and East Malaysia on Borneo", "popDesc": "34.3 million; multicultural society blending Malay, Chinese, and Indian influences" },
  "Thailand": { "flag": "🇹🇭", "colors": ["Red","White","Blue"], "capital": "Bangkok", "region": "Asia", "knownFor": "Ornate temples, beautiful beaches, and vibrant street food", "sizeDesc": "513,120 km²; central plains, mountains in the north, and southern peninsula", "popDesc": "71.8 million; strong tourism-driven economy and rich Buddhist culture" },
  "Colombia": { "flag": "🇨🇴", "colors": ["Yellow","Blue","Red"], "capital": "Bogotá", "region": "South America", "knownFor": "High-quality coffee and rich biodiversity", "sizeDesc": "1.14M km²; spans Andes mountains, Amazon rainforest, and two coastlines", "popDesc": "52 million; diverse culture shaped by indigenous, Spanish, and African roots" },
  "Vietnam": { "flag": "🇻🇳", "colors": ["Red","Yellow"], "capital": "Hanoi", "region": "Asia", "knownFor": "Halong Bay and rapid economic growth", "sizeDesc": "331,212 km²; long, narrow country with extensive coastline along the South China Sea", "popDesc": "100.3 million; young demographic and emerging manufacturing powerhouse" },
  "Uruguay": { "flag": "🇺🇾", "colors": ["Blue","White","Yellow"], "capital": "Montevideo", "region": "South America", "knownFor": "Progressive social policies and high quality of life", "sizeDesc": "176,215 km²; rolling plains and coastal regions", "popDesc": "3.4 million; highly urbanized population with strong European heritage" },
  "Morocco": { "flag": "🇲🇦", "colors": ["Red","Green"], "capital": "Rabat", "region": "Africa", "knownFor": "Historic medinas, the Sahara Desert, and vibrant souks", "sizeDesc": "446,550 km²; spans Atlas Mountains to the Atlantic and Mediterranean coasts", "popDesc": "37.8 million; strategic gateway between Europe and Africa" },
  "Costa Rica": { "flag": "🇨🇷", "colors": ["Blue","White","Red"], "capital": "San José", "region": "North America", "knownFor": "Pioneering eco-tourism and abolished its army", "sizeDesc": "51,100 km²; rugged, volcanic geography covered by dense rainforests", "popDesc": "5.2 million; high standard of living and long life expectancy" },
  "Cyprus": { "flag": "🇨🇾", "colors": ["White","Orange","Green"], "capital": "Nicosia", "region": "Europe", "knownFor": "Mediterranean beaches and ancient archaeological sites", "sizeDesc": "9,251 km²; strategic island in the eastern Mediterranean", "popDesc": "1.2 million; divided island with significant tourism and shipping industries" },
  "Kuwait": { "flag": "🇰🇼", "colors": ["Green","White","Red","Black"], "capital": "Kuwait City", "region": "Asia", "knownFor": "Vast oil wealth and modern skyline", "sizeDesc": "17,818 km²; small desert nation at the tip of the Persian Gulf", "popDesc": "4.3 million; high expat population working in oil and service sectors" },
  "Oman": { "flag": "🇴🇲", "colors": ["Red","White","Green"], "capital": "Muscat", "region": "Asia", "knownFor": "Traditional Arabian culture and peaceful diplomacy", "sizeDesc": "309,500 km²; diverse landscape of deserts, mountains, and long coastlines", "popDesc": "4.6 million; stable society with a growing focus on tourism and trade" },
  "Bulgaria": { "flag": "🇧🇬", "colors": ["White","Green","Red"], "capital": "Sofia", "region": "Europe", "knownFor": "Rose oil production and Black Sea resorts", "sizeDesc": "110,994 km²; Balkan mountains and fertile plains", "popDesc": "6.4 million; aging population with strong Eastern Orthodox traditions" },
  "Serbia": { "flag": "🇷🇸", "colors": ["Red","Blue","White"], "capital": "Belgrade", "region": "Europe", "knownFor": "Crossroads of the Balkans and rich history", "sizeDesc": "88,361 km²; landlocked with significant rivers including the Danube", "popDesc": "6.6 million; recovering economy and vibrant capital city life" },
  "Iran": { "flag": "🇮🇷", "colors": ["Green","White","Red"], "capital": "Tehran", "region": "Asia", "knownFor": "Ancient Persian history and vast energy reserves", "sizeDesc": "1.64M km²; highly mountainous terrain and extensive central deserts", "popDesc": "88.5 million; large, young, and highly educated urban population" },
  "Panama": { "flag": "🇵🇦", "colors": ["Blue","White","Red"], "capital": "Panama City", "region": "North America", "knownFor": "The Panama Canal connecting two oceans", "sizeDesc": "75,417 km²; narrow isthmus with tropical rainforests", "popDesc": "4.4 million; global logistics hub with a booming capital skyline" },
  "Jordan": { "flag": "🇯🇴", "colors": ["Black","White","Green","Red"], "capital": "Amman", "region": "Asia", "knownFor": "The ancient city of Petra and the Dead Sea", "sizeDesc": "89,342 km²; mostly arid desert with strategic access to the Red Sea", "popDesc": "11.3 million; hosts a massive refugee population in a stable monarchy" },
  "Kenya": { "flag": "🇰🇪", "colors": ["Black","Red","Green","White"], "capital": "Nairobi", "region": "Africa", "knownFor": "Wildlife safaris and dominant distance runners", "sizeDesc": "580,367 km²; encompasses savannah, lakelands, and the Great Rift Valley", "popDesc": "54 million; regional economic powerhouse known as the 'Silicon Savannah'" },
  "Bahrain": { "flag": "🇧🇭", "colors": ["Red","White"], "capital": "Manama", "region": "Asia", "knownFor": "Financial hub and Formula 1 racing", "sizeDesc": "780 km²; small archipelago in the Persian Gulf", "popDesc": "1.5 million; diverse expatriate workforce and progressive Gulf economy" },
  "Pakistan": { "flag": "🇵🇰", "colors": ["Green","White"], "capital": "Islamabad", "region": "Asia", "knownFor": "K2 mountain and rich cultural history", "sizeDesc": "881,913 km²; diverse terrain from Arabian Sea coast to the Himalayas", "popDesc": "240 million; world's 5th most populous nation with a young demographic" },
  "Tunisia": { "flag": "🇹🇳", "colors": ["Red","White"], "capital": "Tunis", "region": "Africa", "knownFor": "Ancient ruins of Carthage and Mediterranean resorts", "sizeDesc": "163,610 km²; northernmost country in Africa with access to the Sahara", "popDesc": "12.4 million; highly educated workforce and significant tourism sector" },
  "Ecuador": { "flag": "🇪🇨", "colors": ["Yellow","Blue","Red"], "capital": "Quito", "region": "South America", "knownFor": "The Galápagos Islands and the equator", "sizeDesc": "283,561 km²; features the Andes, Amazon basin, and Pacific coast", "popDesc": "18.1 million; rich indigenous culture and heavy reliance on oil exports" },
  "Dominican Republic": { "flag": "🇩🇴", "colors": ["Blue","White","Red"], "capital": "Santo Domingo", "region": "North America", "knownFor": "Most visited destination in the Caribbean", "sizeDesc": "48,671 km²; shares the island of Hispaniola with Haiti", "popDesc": "11.3 million; rapidly growing economy driven by tourism and agriculture" },
  "Jamaica": { "flag": "🇯🇲", "colors": ["Green","Yellow","Black"], "capital": "Kingston", "region": "North America", "knownFor": "Reggae music and vibrant Caribbean culture", "sizeDesc": "10,991 km²; mountainous island nation known for its lush topography", "popDesc": "2.8 million; significant global cultural influence despite small size" },
  "Sri Lanka": { "flag": "🇱🇰", "colors": ["Yellow","Maroon","Green","Orange"], "capital": "Colombo", "region": "Asia", "knownFor": "Ceylon tea, ancient ruins, and tropical beaches", "sizeDesc": "65,610 km²; island nation south of India with diverse ecosystems", "popDesc": "22.1 million; highly literate population recovering from economic crises" },
  "Lebanon": { "flag": "🇱🇧", "colors": ["Red","White","Green"], "capital": "Beirut", "region": "Asia", "knownFor": "Cedar trees and vibrant Mediterranean culture", "sizeDesc": "10,452 km²; small, mountainous nation on the eastern Mediterranean", "popDesc": "5.4 million; historically a major financial and cultural hub of the Middle East" },
  "Algeria": { "flag": "🇩🇿", "colors": ["Green","White","Red"], "capital": "Algiers", "region": "Africa", "knownFor": "Largest country in Africa and vast Sahara landscapes", "sizeDesc": "2.38M km²; dominated by the Sahara Desert with a fertile northern coast", "popDesc": "45.4 million; economy heavily reliant on significant oil and gas reserves" },
  "Malta": { "flag": "🇲🇹", "colors": ["White","Red"], "capital": "Valletta", "region": "Europe", "knownFor": "Historic fortresses and Mediterranean climate", "sizeDesc": "316 km²; highly dense archipelago south of Italy", "popDesc": "530,000; booming tech, gaming, and tourism industries" },
  "Mauritius": { "flag": "🇲🇺", "colors": ["Red","Blue","Yellow","Green"], "capital": "Port Louis", "region": "Africa", "knownFor": "Luxury resorts and stable democracy", "sizeDesc": "2,040 km²; volcanic island nation in the Indian Ocean", "popDesc": "1.2 million; highly developed and diverse economy" },
  "Bangladesh": { "flag": "🇧🇩", "colors": ["Green","Red"], "capital": "Dhaka", "region": "Asia", "knownFor": "Massive garment industry and the Sundarbans", "sizeDesc": "148,460 km²; low-lying riverine country highly vulnerable to climate change", "popDesc": "170 million; one of the world's most densely populated nations" },
  "Ghana": { "flag": "🇬🇭", "colors": ["Red","Yellow","Green","Black"], "capital": "Accra", "region": "Africa", "knownFor": "Rich Gold Coast history and stable democracy", "sizeDesc": "238,533 km²; spans coastal plains to northern savannas", "popDesc": "33.4 million; major exporter of cocoa, gold, and oil" },
  "Senegal": { "flag": "🇸🇳", "colors": ["Green","Yellow","Red"], "capital": "Dakar", "region": "Africa", "knownFor": "Stable democracy and westernmost point of Africa", "sizeDesc": "196,722 km²; features Sahel landscapes and Atlantic coastline", "popDesc": "17.3 million; vibrant arts scene and growing influence in West Africa" },
  "Tanzania": { "flag": "🇹🇿", "colors": ["Green","Yellow","Blue","Black"], "capital": "Dodoma", "region": "Africa", "knownFor": "Mount Kilimanjaro and the Serengeti", "sizeDesc": "947,303 km²; incredible wildlife reserves and the island of Zanzibar", "popDesc": "65.4 million; rapidly growing population with diverse ethnic groups" },
  "Bolivia": { "flag": "🇧🇴", "colors": ["Red","Yellow","Green"], "capital": "Sucre", "region": "South America", "knownFor": "Salar de Uyuni, the world's largest salt flat", "sizeDesc": "1.09M km²; landlocked nation spanning high Andes to Amazon basin", "popDesc": "12.2 million; largest proportion of indigenous peoples in South America" },
  "Cuba": { "flag": "🇨🇺", "colors": ["Blue","White","Red"], "capital": "Havana", "region": "North America", "knownFor": "Classic cars, cigars, and revolutionary history", "sizeDesc": "109,884 km²; largest island in the Caribbean", "popDesc": "11.2 million; strong healthcare and education systems despite economic embargoes" },
  "El Salvador": { "flag": "🇸🇻", "colors": ["Blue","White"], "capital": "San Salvador", "region": "North America", "knownFor": "Volcanoes and adoption of Bitcoin", "sizeDesc": "21,041 km²; smallest and most densely populated country in Central America", "popDesc": "6.3 million; large diaspora contributing heavily via remittances" },
  "Guatemala": { "flag": "🇬🇹", "colors": ["Blue","White"], "capital": "Guatemala City", "region": "North America", "knownFor": "Heart of the Mayan world and spectacular volcanoes", "sizeDesc": "108,889 km²; rugged, forested terrain and ancient ruins", "popDesc": "17.1 million; largest economy in Central America with rich indigenous heritage" },
  "Honduras": { "flag": "🇭🇳", "colors": ["Blue","White"], "capital": "Tegucigalpa", "region": "North America", "knownFor": "Ancient Mayan ruins at Copán", "sizeDesc": "112,492 km²; mountainous terrain with Caribbean and Pacific coastlines", "popDesc": "10.4 million; economy heavily dependent on agriculture and remittances" },
  "Paraguay": { "flag": "🇵🇾", "colors": ["Red","White","Blue"], "capital": "Asunción", "region": "South America", "knownFor": "Guaraní culture and vast hydroelectric power", "sizeDesc": "406,752 km²; landlocked nation divided by the Paraguay River", "popDesc": "6.8 million; major exporter of soybeans and beef" },
  "Uganda": { "flag": "🇺🇬", "colors": ["Black","Yellow","Red"], "capital": "Kampala", "region": "Africa", "knownFor": "Mountain gorillas and Lake Victoria", "sizeDesc": "241,038 km²; landlocked but water-rich 'Pearl of Africa'", "popDesc": "47.2 million; extremely young population and rapidly growing economy" },
  "Ivory Coast": { "flag": "🇨🇮", "colors": ["Orange","White","Green"], "capital": "Yamoussoukro", "region": "Africa", "knownFor": "World's leading producer of cocoa beans", "sizeDesc": "322,463 km²; lush tropical coastlines and interior savannas", "popDesc": "28.1 million; economic powerhouse of Francophone West Africa" },
  "Belarus": { "flag": "🇧🇾", "colors": ["Red","Green","White"], "capital": "Minsk", "region": "Europe", "knownFor": "Heavy industry and strategic Eastern European location", "sizeDesc": "207,600 km²; flat, landlocked country with extensive forests and lakes", "popDesc": "9.2 million; highly industrialized economy with close ties to Russia" },
  "Azerbaijan": { "flag": "🇦🇿", "colors": ["Blue","Red","Green"], "capital": "Baku", "region": "Asia", "knownFor": "Caspian Sea oil wealth and distinct regional culture", "sizeDesc": "86,600 km²; situated at the crossroads of Eastern Europe and Western Asia", "popDesc": "10.1 million; rapidly modernizing capital fueled by energy exports" },
  "Rwanda": { "flag": "🇷🇼", "colors": ["Blue","Yellow","Green"], "capital": "Kigali", "region": "Africa", "knownFor": "Fastest-growing tech hub in Africa, 'Land of a Thousand Hills'", "sizeDesc": "26,338 km²; highly elevated, dense, and green geography", "popDesc": "13.2 million; remarkable post-conflict economic and social recovery" },
  "Uzbekistan": { "flag": "🇺🇿", "colors": ["Blue","White","Green","Red"], "capital": "Tashkent", "region": "Asia", "knownFor": "Heart of the ancient Silk Road and growing economy", "sizeDesc": "448,978 km²; doubly landlocked country with vast deserts and historic cities", "popDesc": "36.2 million; largest population in Central Asia undergoing rapid modernization" }
};

let content = fs.readFileSync('src/data/countries.ts', 'utf-8');

for (const [name, info] of Object.entries(data)) {
  const blockRegex = new RegExp(`(name:\\s*"${name}",[\\s\\S]*?stats:\\s*\\{[\\s\\S]*?\\}\\s*,\\s*\\n\\s*\\})`);
  const match = content.match(blockRegex);
  
  if (match) {
    let block = match[1];
    
    // Update simple string fields
    if (info.flag) block = block.replace(/flag:\s*".*?"/, `flag: "${info.flag}"`);
    if (info.colors) block = block.replace(/flagColors:\s*\[.*?\]/, `flagColors: ${JSON.stringify(info.colors)}`);
    if (info.capital) block = block.replace(/capital:\s*".*?"/, `capital: "${info.capital}"`);
    if (info.region) block = block.replace(/region:\s*".*?"/, `region: "${info.region}"`);
    if (info.knownFor) block = block.replace(/knownFor:\s*".*?"/, `knownFor: "${info.knownFor}"`);
    
    // Update size desc
    block = block.replace(/size:\s*\{\s*score:\s*(\d+),\s*description:\s*".*?"\s*\}/, `size: { score: $1, description: "${info.sizeDesc}" }`);
    
    // Update pop desc
    block = block.replace(/population:\s*\{\s*score:\s*(\d+),\s*description:\s*".*?"\s*\}/, `population: { score: $1, description: "${info.popDesc}" }`);
    
    content = content.replace(blockRegex, block);
  }
}

fs.writeFileSync('src/data/countries.ts', content);
console.log('Done!');
